### ISSUE TITLE
Instrument doesn't works if decimal points is in commas (Localisation issue)

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab-android#1517]
**Actual Behaviour**
Values are not shown properly if phone language is set to within Europe. 
The same issue happens in oscilloscope, power source, multimeter and others.

**Expected Behaviour**
Calculation of values should still happen regardless of the language set on the phone.

**Steps to reproduce it**
Set your phone default language to English (Germany) and open the app.

**Screenshots of the issue**
![photo_2019-01-03_01-11-22](https://user-images.githubusercontent.com/11439477/50603161-8b192200-0ef4-11e9-9acf-cf787200b82c.jpg)

**Comment by cweitat** [comment]
Solution could be detect the language/country of the phone settings and show the values respectively.

**Comment by Yahhi** [comment]
I want to work on this issue

**Comment by cweitat** [comment]
@Yahhi go ahead

**Comment by Yahhi** [comment]
There are even places where the app crashes with something like this: 
FATAL EXCEPTION: main
    Process: io.pslab, PID: 14645
    java.lang.NumberFormatException: For input string: "-0,66"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:539)
        at java.lang.Double.valueOf(Double.java:503)
        at io.pslab.others.FloatSeekBar.getValue(FloatSeekBar.java:42)
        at io.pslab.fragment.TimebaseTriggerFragment$2.onProgressChanged(TimebaseTriggerFragment.java:144)
...
The main reason for all this behavior is the process of digit limitation (2 digits after the dot). DecimalFormat and Double.valueOf on the result are used everywhere, It uses default locale values for creating strings, but can't get a value from a string with a comma. I suggest using a different approach to limit digits.
