### ISSUE TITLE
Crash : App Crashes when Logged data of Lux Meter clicked

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1641]
**Actual Behaviour**

App crashing when logged data of Lux meter clicked

**Expected Behaviour**

The app should not crash

**Steps to reproduce it**

Record Lux meter and click on logged data

**LogCat for the issue**

Caused by: java.util.IllegalFormatConversionException: f != java.lang.String
        at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4402)
        at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2897)
        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2844)
        at java.util.Formatter.format(Formatter.java:2523)
        at java.util.Formatter.format(Formatter.java:2458)
        at java.lang.String.format(String.java:2814)
        at io.pslab.fragment.LuxMeterDataFragment.plotAllRecordedData(LuxMeterDataFragment.java:186)
        at io.pslab.fragment.LuxMeterDataFragment.onResume(LuxMeterDataFragment.java:139)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7385)

**Screenshots of the issue**

![crash](https://user-images.githubusercontent.com/37077735/55037571-6d32f900-4fdb-11e9-98cd-b43986424b0c.jpg)

**Would you like to work on the issue?**

Yes

**Comment by ho-dor** [comment]
This crash occured due to some debugging steps i took to solve another issue .
