### ISSUE TITLE
App crashed on Opening Thermometer

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1752]
**Actual Behaviour**

App crashes on opening thermometer

**Expected Behaviour**
App should not crash

**Steps to reproduce it**
Open Thermometer

**LogCat for the issue**
2019-05-28 18:23:22.508 31731-31731/io.pslab E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.pslab, PID: 31731
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.pslab/io.pslab.activity.ThermometerActivity}: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class com.biansemao.widget.ThermometerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class com.biansemao.widget.ThermometerView
     Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class com.biansemao.widget.ThermometerView
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.biansemao.widget.ThermometerView" on path: DexPathList[[zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/base.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_dependencies_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_resources_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_0_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_1_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_2_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_3_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_4_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_5_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_6_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_7_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_8_apk.apk", zip file "/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/lib/arm, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/base.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
2019-05-28 18:23:22.512 31731-31731/io.pslab E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at io.pslab.fragment.ThermometerDataFragment.onCreateView(ThermometerDataFragment.java:60)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1356)
        at android.app.Activity.performStart(Activity.java:7052)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2824)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/io.pslab-9831tt8NZpCK-gw1omhL5A==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:702)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:736)
        at android.app.LoadedApk.getResources(LoadedApk.java:963)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2285)
2019-05-28 18:23:22.513 31731-31731/io.pslab E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5753)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
        		... 6 more

**Would you like to work on the issue?**
@ho-dor Kindly have a look at this

**Comment by ho-dor** [comment]
Solved in #1754 . @neel1998 close this.
