### ISSUE TITLE
App crashes on clicking export data option of multimeter

### ISSUE THREAD

**Issue by neel1998** [fossasia/pslab-android#1759]
**Actual Behaviour**
App crashes on clicking export data option of multimeter

**Expected Behaviour**
App should not crash and a log file should be created

**Steps to reproduce it**
1. Record data in multimeter
2. Pause and select export data option

**LogCat for the issue**
2019-05-31 12:45:57.070 23742-23742/io.pslab E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.pslab, PID: 23742
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
        at io.pslab.others.CSVLogger.writeCSVFile(CSVLogger.java:83)
        at io.pslab.activity.MultimeterActivity.onOptionsItemSelected(MultimeterActivity.java:428)
        at android.app.Activity.onMenuItemSelected(Activity.java:3469)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:436)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:204)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3153)
        at android.widget.AbsListView$3.run(AbsListView.java:4068)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Screenshots of the issue**
![20190531_124551](https://user-images.githubusercontent.com/32041242/58688770-00552a00-83a3-11e9-830d-50c01e609b99.gif)

**Would you like to work on the issue?**
yes

**Comment by neel1998** [comment]
@CloudyPadmal  why do we have a pause button? Shouldn't it be made like other devices, where we have a stop button and clicking on it creates a csv file of logged data?

**Comment by CloudyPadmal** [comment]
@neel1998 yes, it should be a stop button

**Comment by neel1998** [comment]
@CloudyPadmal  i am thinking of inheriting multimeter from PSLab sensor class to avoid redundancy . Does it sound right?

**Comment by CloudyPadmal** [comment]
That would be hard. As PSLab Sensor class got graphs and all which doesn't come with Multimeter. We can stick with the existing activity for Multimeter.

**Comment by neel1998** [comment]
@CloudyPadmal  but if we want to show log data of multimeter in log data activity and playback that data.. That would become complex using current class, since realm data storing and playing back is already there in PSLab sensor , i think we can use it. This is what i think. Please give your suggestion

**Comment by neel1998** [comment]
@CloudyPadmal  to resolve the #1373 I was thinking of recording data at certain time interval (say 500 ms) when record button is pressed. We will record the data of the element to which the multimeter knob is pointing .Does this sound okay ?

**Comment by neel1998** [comment]
Also should i remove the show logged data option from multimeter menu since we are not displaying multimeter logs in datalogger activity

**Comment by CloudyPadmal** [comment]
> @CloudyPadmal but if we want to show log data of multimeter in log data activity and playback that data.. That would become complex using current class, since realm data storing and playing back is already there in PSLab sensor , i think we can use it. This is what i think. Please give your suggestion

If that's the case, best thing is to make a super class with all the graph and data storing functionalities and have `PSLabSensor` class inherit that.

**Comment by CloudyPadmal** [comment]
> @CloudyPadmal to resolve the #1373 I was thinking of recording data at certain time interval (say 500 ms) when record button is pressed. We will record the data of the element to which the multimeter knob is pointing .Does this sound okay ?

Let's give user the option to set recording interval from configurations

**Comment by neel1998** [comment]
> > @CloudyPadmal but if we want to show log data of multimeter in log data activity and playback that data.. That would become complex using current class, since realm data storing and playing back is already there in PSLab sensor , i think we can use it. This is what i think. Please give your suggestion
> 
> If that's the case, best thing is to make a super class with all the graph and data storing functionalities and have `PSLabSensor` class inherit that.

Do we actually need to show multimeter logs in data logger activity. I don't see any use of replaying multimeter data

**Comment by neel1998** [comment]
> > @CloudyPadmal to resolve the #1373 I was thinking of recording data at certain time interval (say 500 ms) when record button is pressed. We will record the data of the element to which the multimeter knob is pointing .Does this sound okay ?
> 
> Let's give user the option to set recording interval from configurations

Should i open another issue regarding this or work with the already open one with continuous logging?

**Comment by CloudyPadmal** [comment]
@neel1998 , let's see. May be we can plot the values in a graph in a timely manner? :thinking: That way we can replay.

**Comment by neel1998** [comment]
> > @CloudyPadmal but if we want to show log data of multimeter in log data activity and playback that data.. That would become complex using current class, since realm data storing and playing back is already there in PSLab sensor , i think we can use it. This is what i think. Please give your suggestion
> 
> If that's the case, best thing is to make a super class with all the graph and data storing functionalities and have `PSLabSensor` class inherit that.

Please explain this a bit, because i think we can do this for all the instruments that inherit `PSLabSensor`

**Comment by neel1998** [comment]
> @neel1998 , let's see. May be we can plot the values in a graph in a timely manner?  That way we can replay. And open a new issue for the configuration part and work on it..

Yes that can be done and would look good. But for that we need to store logs in realm and that would be easier if we had a parent class with all the methods

**Comment by neel1998** [comment]
> > @CloudyPadmal to resolve the #1373 I was thinking of recording data at certain time interval (say 500 ms) when record button is pressed. We will record the data of the element to which the multimeter knob is pointing .Does this sound okay ?
> 
> Let's give user the option to set recording interval from configurations

What should be the range for the interval?

**Comment by CloudyPadmal** [comment]
Multimeter extends GraphRealmClass 
PSLabSensor extends GraphRealmClass
LuxSensor extends PSLabSensor

Makes sense? Java.

**Comment by neel1998** [comment]
@CloudyPadmal yes I will try implementing the GraphRealmClass. But I think I will fix #1762 with current structure and then raise a new issue to add new parent class. Will it be okay?
