### ISSUE TITLE
App crashes when sin wave Logic analyser Analysed with CH3. 

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1829]
**Actual Behaviour**

App is crashing when sin wave analysed with logic analyser on CH3.

**Expected Behaviour**

**Steps to reproduce it**

Open wave generator use Wave 1 and set any freq and view with logic analyser.
Press analyse on logic analyser.

**Logs**

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
        at io.pslab.fragment.LALogicLinesFragment$1.run(LALogicLinesFragment.java:134)
        at java.lang.Thread.run(Thread.java:764)
2019-06-25 16:09:07.903 6971-7131/io.pslab E/AndroidRuntime: FATAL EXCEPTION: Thread-14
    Process: io.pslab, PID: 6971
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
        at io.pslab.fragment.LALogicLinesFragment$1.run(LALogicLinesFragment.java:134)
        at java.lang.Thread.run(Thread.java:764)
2019-06-25 16:09:07.904 6971-7665/io.pslab E/AndroidRuntime: FATAL EXCEPTION: Thread-24
    Process: io.pslab, PID: 6971
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
        at io.pslab.fragment.LALogicLinesFragment$1.run(LALogicLinesFragment.java:134)
        at java.lang.Thread.run(Thread.java:764)`

**Would you like to work on the issue?**

Yes.

**Comment by CloudyPadmal** [comment]
@ho-dor please add crash logs if possible

**Comment by neel1998** [comment]
I think this will be solved with #1825 since that issue is intended for proper functionality of Logic Analyzer

**Comment by ankitsharma5652** [comment]
I would like to solve this issue.

**Comment by ho-dor** [comment]
@ankitsharma5652 @neel1998 is working on this in #1825 as mentioned above
