### ISSUE TITLE
App crashes when true is passed to runInitSequence method

### ISSUE THREAD

**Issue by akarshan96** [fossasia/pslab-android#183]
**Actual Behaviour**

Calling runInitSequence method and passing true as the argument is causing the app to crash.

**Expected Behaviour**

The app shouldn't crash when runInitSequence is called. 

**Steps to reproduce it**

Create an object of ScienceLab and call runInitSequence method and pass true to it.

**LogCat for the issue**

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.fossasia.pslab, PID: 11243
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia.pslab/org.fossasia.pslab.activity.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: src.length=16384 srcPos=0 dst.length=16 dstPos=1 length=16
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                      at android.app.ActivityThread.access$900(ActivityThread.java:153)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5438)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                   Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=16384 srcPos=0 dst.length=16 dstPos=1 length=16
                      at java.lang.System.arraycopy(Native Method)
                      at org.fossasia.pslab.communication.CommunicationHandler.read(CommunicationHandler.java:134)
                      at org.fossasia.pslab.communication.PacketHandler.read(PacketHandler.java:157)
                      at org.fossasia.pslab.communication.ScienceLab.readFlash(ScienceLab.java:2252)
                      at org.fossasia.pslab.communication.ScienceLab.runInitSequence(ScienceLab.java:170)
                      at org.fossasia.pslab.communication.ScienceLab.<init>(ScienceLab.java:92)
                      at org.fossasia.pslab.others.ScienceLabCommon.openDevice(ScienceLabCommon.java:22)
                      at org.fossasia.pslab.activity.MainActivity.onCreate(MainActivity.java:80)
                      at android.app.Activity.performCreate(Activity.java:6303)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                      at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5438) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
```

**Screenshots of the issue**

None

**Would you like to work on the issue?**

@viveksb007 will work on it.

**Comment by viveksb007** [comment]
Fixed in #185
