### ISSUE TITLE
Crash on opening gyroscope configuration menu

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1872]
**Actual Behaviour**

crash when configuration menu is opened in gyroscope

**Expected Behaviour**

crash should not happen

**Steps to reproduce it**

Open gyroscope configuration

**LogCat for the issue**

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.support.v7.preference.EditTextPreference.getText()' on a null object reference
        at io.pslab.fragment.GyroscopeSettingsFragment.onResume(GyroscopeSettingsFragment.java:51)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7583)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4007)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4047) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7073) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974) 

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes

**Comment by ankitsharma5652** [comment]
I found issue. Issue is with key we are using GyroscopeSettingsFragment and XML.

We using "setting_gyro_update_period" in class and  "setting_lux_update" in XML.

Same issue with "high_limit_lux", "setting_lux_sensor_gain" in XML
