### ISSUE TITLE
App crash on Creating Config File

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/pslab-android#2008]
**Actual Behaviour**
When we try to Create Config File the app crashes.

**Expected Behaviour**
Config File should be created

**Steps to reproduce it**
1.Open Generate Config File from Navigation Drawer
2.Give some value to time interval
3.Click on Create Config File

**LogCat for the issue**
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.pslab, PID: 20018
    java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
        at io.pslab.activity.CreateConfigActivity.createConfigFile(CreateConfigActivity.java:187)
        at io.pslab.activity.CreateConfigActivity.access$800(CreateConfigActivity.java:31)
        at io.pslab.activity.CreateConfigActivity$3.onClick(CreateConfigActivity.java:111)
        at android.view.View.performClick(View.java:5619)
        at android.view.View$PerformClick.run(View.java:22298)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)`

**Would you like to work on the issue?**
Yes, but please guide me for the actual behaviour for this

**Comment by kshitiz-kumar** [comment]
Can share the ss or gif  because everything is working fine for me.

**Comment by amit6663** [comment]
i want to work on this issue. @dheerajkotwani , @asitava1998

**Comment by ho-dor** [comment]
Unable to produce this crash. @CloudyPadmal can you verify or this can be closed.

**Comment by Low012** [comment]
It crashes on devices with API level 25 and below.
