### ISSUE TITLE
Oscilloscope: App crashes as soon as record button is clicked while using built-in mic. 

### ISSUE THREAD

**Issue by hyPnOtICDo0g** [fossasia/pslab-android#2032]
**Actual Behaviour**
Oscilloscope: The app crashes as soon as the record button is clicked while using the built-in mic.

**Expected Behaviour**
The shouldn't crash when the record button is clicked, and I should be able to obtain the .csv files after recording.

**Steps to reproduce it**
• Open the app & click on the Oscilloscope.
• Switch to built-in mic & click on record button.
• The app crashes.

**Screenshots of the issue**
![15-12-2019_08-39-19_trim ConvGif](https://user-images.githubusercontent.com/44530973/70857556-aa973800-1f16-11ea-9ee0-a1d848b75b21.gif)

Device used - Lenovo Phab 2
Android Version - 6.0

**Would you like to work on the issue?**
No.

**Comment by ho-dor** [comment]
Can you share the logcat please @hyPnOtiC-d00g

**Comment by ho-dor** [comment]
I am unable to reproduce this error @CloudyPadmal this is same as #2081. Working fine on my device.

**Comment by CloudyPadmal** [comment]
I see. @ho-dor may be it's some permission issue in microphone? :thinking: 

Sadly we can't expect community to share logcats. Unless they "Report" it, we could see it from Google Play console. (Couldn't see any as noone has "Report"ed it yet) Let's ask to report it.

**Comment by dheerajkotwani** [comment]
The Issue is there.
Clicking on use in-built mic and then start recording.
**Permission for mic given to the app**

**LogCat**
`E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: io.pslab, PID: 8223
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:318)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;[Ljava/lang/CharSequence;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
        at io.pslab.activity.OscilloscopeActivity$CaptureTask.doInBackground(OscilloscopeActivity.java:1120)
        at io.pslab.activity.OscilloscopeActivity$CaptureTask.doInBackground(OscilloscopeActivity.java:960)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760) `

**Comment by Low012** [comment]
String.join was added with API level 26. The min API level of the app is set to 23. I can reproduce the issue on a device with Android 7.1 (API level 25).

I can work on this issue.
