### ISSUE TITLE
App crashes on devices with German locale when previously recorded data is loaded

### ISSUE THREAD

**Issue by Low012** [fossasia/pslab-android#2046]
**Actual Behaviour**

App crashes when recorded data (for example in the logic analyser) is loaded and the device is set to German locale.

**Expected Behaviour**

The app should load the data and display it without crashing.

**Steps to reproduce it**

* Set device to German locale.
* Record some data in the logic analyser screen.
* Try to load the data again.

**LogCat for the issue**

`    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.pslab/io.pslab.activity.LogicalAnalyzerActivity}: java.lang.NumberFormatException: For input string: "0,00"
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
     Caused by: java.lang.NumberFormatException: For input string: "0,00"
        at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
        at java.lang.Double.valueOf(Double.java:511)
        at io.pslab.fragment.LALogicLinesFragment.setPlayBackData(LALogicLinesFragment.java:273)
        at io.pslab.fragment.LALogicLinesFragment.onCreateView(LALogicLinesFragment.java:209)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1270)
        at android.app.Activity.performStart(Activity.java:6704)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2641)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6165) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) `

**Would you like to work on the issue?**

I could definitely **help** solving the issue. I think the root cause of the crash is that data is written with the default locale (German in my case) where 1.23 is written as 1,23 which causes all kinds of problems in CSV files.

**Comment by Low012** [comment]
I am currently working on this issue, I will open a PR when done.
