### ISSUE TITLE
App crashes when coming back from some specific Application after changing screen orientation

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-android#207]
**Actual Behaviour**

App crashes when coming back from some specific application to Application fragment after changing screen orientation

**Expected Behaviour**

App shouldn't crash

**Steps to reproduce it**

Go to Application Fragment, open any application, change screen orientation and go back. App would crash.

**LogCat for the issue**

```
06-20 22:18:50.788 14533-14533/org.fossasia.pslab E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: org.fossasia.pslab, PID: 14533
                                                                    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                        at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
                                                                        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
                                                                        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:649)
                                                                        at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
                                                                        at org.fossasia.pslab.fragment.ApplicationsFragment.onConfigurationChanged(ApplicationsFragment.java:164)
                                                                        at android.support.v4.app.Fragment.performConfigurationChanged(Fragment.java:2261)
                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchConfigurationChanged(FragmentManager.java:2960)
                                                                        at android.support.v4.app.FragmentController.dispatchConfigurationChanged(FragmentController.java:304)
                                                                        at android.support.v4.app.FragmentActivity.onConfigurationChanged(FragmentActivity.java:308)
                                                                        at android.support.v7.app.AppCompatActivity.onConfigurationChanged(AppCompatActivity.java:160)
                                                                        at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4219)
                                                                        at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:4322)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Would you like to work on the issue?**

Yes

**Comment by viveksb007** [comment]
Fixed in #208
