### ISSUE TITLE
Logic Analyzer does not open up

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#2257]
**Actual Behaviour**

Opening Logic Analyzer crashes the app

**Expected Behaviour**

App should not crash

**Steps to reproduce it**

Open Logic Analyzer

**LogCat for the issue**

```
2021-10-15 08:08:32.520 11799-11799/io.pslab E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.pslab, PID: 11799
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.pslab/io.pslab.activity.LogicalAnalyzerActivity}: android.view.InflateException: Binary XML file line #43 in io.pslab:layout/activity_logic_analyzer: Could not inflate Behavior subclass android.support.design.widget.BottomSheetBehavior
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.view.InflateException: Binary XML file line #43 in io.pslab:layout/activity_logic_analyzer: Could not inflate Behavior subclass android.support.design.widget.BottomSheetBehavior
     Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass android.support.design.widget.BottomSheetBehavior
        at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:649)
        at androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2896)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1740)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:112)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1256)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at io.pslab.activity.LogicalAnalyzerActivity.onCreate(LogicalAnalyzerActivity.java:66)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: android.support.design.widget.BottomSheetBehavior
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:642)
2021-10-15 08:08:32.522 11799-11799/io.pslab E/AndroidRuntime: 	... 27 more
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.BottomSheetBehavior" on path: DexPathList[[zip file "/data/app/~~cOqzHTaRoTsoL4SjEKnenA==/io.pslab-Mpttrzt764u8V54E-9cY9g==/base.apk"],nativeLibraryDirectories=[/data/app/~~cOqzHTaRoTsoL4SjEKnenA==/io.pslab-Mpttrzt764u8V54E-9cY9g==/lib/x86, /data/app/~~cOqzHTaRoTsoL4SjEKnenA==/io.pslab-Mpttrzt764u8V54E-9cY9g==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 30 more
```

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

N/A

**Comment by Jdbarad** [comment]
I like to work on this issue, can you help to where to start?
