### ISSUE TITLE
Wavegenerator does not open up

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-android#2258]
**Actual Behaviour**

Opening wave generator instrument crashes the app

**Expected Behaviour**

App should not crash

**Steps to reproduce it**

Open wave generator

**LogCat for the issue**

```
2021-10-15 08:58:48.324 12478-12478/io.pslab E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.pslab, PID: 12478
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.pslab/io.pslab.activity.WaveGeneratorActivity}: android.view.InflateException: Binary XML file line #29 in io.pslab:layout/activity_wave_generator_main: Binary XML file line #34 in io.pslab:layout/wave_generator_seekbar: Error inflating class com.warkiz.widget.IndicatorSeekBar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.view.InflateException: Binary XML file line #29 in io.pslab:layout/activity_wave_generator_main: Binary XML file line #34 in io.pslab:layout/wave_generator_seekbar: Error inflating class com.warkiz.widget.IndicatorSeekBar
     Caused by: android.view.InflateException: Binary XML file line #34 in io.pslab:layout/wave_generator_seekbar: Error inflating class com.warkiz.widget.IndicatorSeekBar
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1261)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1261)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at io.pslab.activity.WaveGeneratorActivity.onCreate(WaveGeneratorActivity.java:214)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
2021-10-15 08:58:48.324 12478-12478/io.pslab E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: the Argument: TICK COUNT must be limited between (0-50), Now is 51
        at com.warkiz.widget.IndicatorSeekBar.collectTicksInfo(IndicatorSeekBar.java:272)
        at com.warkiz.widget.IndicatorSeekBar.initParams(IndicatorSeekBar.java:262)
        at com.warkiz.widget.IndicatorSeekBar.<init>(IndicatorSeekBar.java:149)
        	... 36 more
```

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

N/A

**Comment by Jdbarad** [comment]
Can I do Work On these Issues?
