### ISSUE TITLE
App crash on opening ROBOTIC ARM

### ISSUE THREAD

**Issue by suman-somu** [fossasia/pslab-android#2279]
**Actual Behaviour**

Opening ROBOTIC ARM crashes the app

**Expected Behaviour**

App shouldn't crash

**Steps to reproduce it**

Open ROBOTIC ARM

**LogCat for the issue**

11-06 10:53:15.958  6197  6197 E AndroidRuntime: FATAL EXCEPTION: main
11-06 10:53:15.958  6197  6197 E AndroidRuntime: Process: io.pslab, PID: 6197
11-06 10:53:15.958  6197  6197 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.pslab/io.pslab.activity.RoboticArmActivity}: android.view.InflateException: Binary XML file line #9 in io.pslab:layout/activity_robotic_arm: Binary XML file line #9 in io.pslab:layout/activity_robotic_arm: Error inflating class android.support.design.widget.CoordinatorLayout
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3735)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3903)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:255)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8215)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #9 in io.pslab:layout/activity_robotic_arm: Binary XML file line #9 in io.pslab:layout/activity_robotic_arm: Error inflating class android.support.design.widget.CoordinatorLayout
11-06 10:53:15.958  6197  6197 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #9 in io.pslab:layout/activity_robotic_arm: Error inflating class android.support.design.widget.CoordinatorLayout
11-06 10:53:15.958  6197  6197 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.support.design.widget.CoordinatorLayout
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:454)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:813)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:657)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at io.pslab.activity.RoboticArmActivity.onCreate(RoboticArmActivity.java:109)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8151)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8135)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3704)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3903)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:255)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8215)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.CoordinatorLayout" on path: DexPathList[[zip file "/data/app/~~welsSkYPmsxgPdw7AGJ7Vw==/io.pslab-gn6-_DIOqzhQURc7bTSLAQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~welsSkYPmsxgPdw7AGJ7Vw==/io.pslab-gn6-_DIOqzhQURc7bTSLAQ==/lib/arm64, /data/app/~~welsSkYPmsxgPdw7AGJ7Vw==/io.pslab-gn6-_DIOqzhQURc7bTSLAQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /vendor/lib64, /odm/lib64]]
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-06 10:53:15.958  6197  6197 E AndroidRuntime: 	... 26 more

**Screenshots of the issue**

https://user-images.githubusercontent.com/75962762/140598609-ecbfbf6b-e13c-45ec-a81a-a168792d5cb0.mp4

**Would you like to work on the issue?**
No

**Comment by suman-somu** [comment]
the log file is not good to read
