### ISSUE TITLE
App crashes if unknown host is entered

### ISSUE THREAD

**Issue by marcnause** [fossasia/pslab-android#2587]
**Actual Behaviour**

The app crashes if the user enters an invalid host address.

**Expected Behaviour**

The app never crashes due to user input.

**Steps to reproduce it**

1. Start app
2. Choose "Connect Device" in the Navigation Drawer
3. Tap "WIFI" button
4. Enter ".lo"
5. Tap "CONNECT" button

**LogCat for the issue**
```
FATAL EXCEPTION: AsyncTask #2
Process: io.pslab, PID: 26126
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalArgumentException: Invalid URL host: ".lo"
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1338)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at io.pslab.fragment.ESPFragment$ESPTask.doInBackground(ESPFragment.java:101)
	at io.pslab.fragment.ESPFragment$ESPTask.doInBackground(ESPFragment.java:87)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	at java.lang.Thread.run(Thread.java:1012) 
```

**Screenshots of the issue**

<img src="https://github.com/user-attachments/assets/6807477b-1aa1-435e-a6b4-7ff9b808609e" width="400" />

**Would you like to work on the issue?**

Yes.

**Comment by samruddhi-Rahegaonkar** [comment]
Issue is Still Encountering.

**Comment by samruddhi-Rahegaonkar** [comment]
@marcnause Should I check ? Assign this to me please.

**Comment by marcnause** [comment]
> @marcnause Should I check ? Assign this to me please.

There is a pending pull request: https://github.com/fossasia/pslab-android/pull/2588

I tried to add you as a reviewer, but that did not work. Please feel free to test the automatically generated APK and comment the PR nevertheless.
